on:
  workflow_dispatch: {}

jobs:
  exe:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.32'
        distribution: strawberry
    - run: cpanm PAR Win32::NetResource Win32::Daemon Win32::Service Date::Manip
    - run: cpanm --installdeps PAR::Packer
    - run: |
        $WebClient = New-Object System.Net.WebClient
        $WebClient.DownloadFile("http://www.cpan.org/authors/id/R/RS/RSCHUPP/PAR-Packer-1.058.tar.gz","C:\temp\packer.tgz")
        c:
        cd \temp
        ptar -xvzf packer.tgz
        cd PAR-Packer-1.058
        (Get-Item .).FullName
        dir
        perl Makefile.PL
        gmake
        gmake install
      shell: pwsh
    - run: perl winconfig.pl
    - run: |
        cd plugins-scripts
        pp -M PerlIO -M Digest::MD5 -M Encode::Encoding -M Encode::Unicode -M Encode::Unicode::UTF7 -M Net::Domain -M Win32::NetResource -M Win32::Daemon -M Time::Piece -M Time::Local -M Win32::EventLog -M Win32::TieRegistry -M Win32::WinError -M Date::Manip -M Win32::OLE -o check_logfiles.exe check_logfiles
      shell: pwsh
    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: "plugins-scripts"
        if-no-files-found: error
